add_newline = false

format = """
$time\
$directory\
$git_branch\
$git_status\
$kubernetes\
$cmd_duration\
$character"""

[time]
disabled = false
format = "[$time]($style) "
time_format = "%T"
style = "bold yellow"

[directory]
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'

[kubernetes]
disabled = false
format = 'on [󱃾 $context\($namespace\)](bold cyan) '

[cmd_duration]
min_time = 2000
format = "took [$duration](bold yellow) "

[character]
success_symbol = "[➜ ](bold green)"
error_symbol = "[➜ ](bold red)"
